version: '3'
services:
  postgres:
    image: postgres:9.3
    ports:
        - "5432:5432"
    env_file:
      - .env
    volumes:
        - postgres-data:/var/lib/postgresql/data
  confluence:
    build: .
    image: webinventions/atlassian-confluence:6.13.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - .env
    volumes:
      - confluence-data:/var/atlassian/confluence/data
volumes:
  postgres-data:
  confluence-data: